export const HIRING_MAN_REQUEST = "HIRING_MAN_REQUEST";
export const HIRING_MAN_SUCCESS = "HIRING_MAN_SUCCESS";
export const HIRING_MAN_FAIL = "HIRING_MAN_FAIL";
export const HIRING_MAN_RESET = "HIRING_MAN_RESET";

export const HIRINGMAN_FORM_REQUEST = "HIRINGMAN_FORM_REQUEST";
export const HIRINGMAN_FORM_SUCCESS = "HIRINGMAN_FORM_SUCCESS";
export const HIRINGMAN_FORM_FAIL = "HIRINGMAN_FORM_FAIL";

export const ACCEPT_HIRING_MAN_REQUEST = "ACCEPT_HIRING_MAN_REQUEST";
export const ACCEPT_HIRING_MAN_SUCCESS = "ACCEPT_HIRING_MAN_SUCCESS";
export const ACCEPT_HIRING_MAN_FAIL = "ACCEPT_HIRING_MAN_FAIL";

export const MAN_ADDRESS = "MAN_ADDRESS";

export const LIST_HIRING_MAN_REQUEST = "LIST_HIRING_MAN_REQUEST";
export const LIST_HIRING_MAN_SUCCESS = "LIST_HIRING_MAN_SUCCESS";
export const LIST_HIRING_MAN_FAIL = "LIST_HIRING_MAN_FAIL";
export const LIST_HIRING_MAN_RESET = "LIST_HIRING_MAN_RESET";

export const ALL_MAN_DETAILS_REQUEST = "ALL_MAN_DETAILS_REQUEST";
export const ALL_MAN_DETAILS_SUCCESS = "ALL_MAN_DETAILS_SUCCESS";
export const ALL_MAN_DETAILS_FAIL = "ALL_MAN_DETAILS_FAIL";
