export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";

export const ORDER_ALL_REQUEST = "ORDER_ALL_REQUEST";
export const ORDER_ALL_SUCCESS = "ORDER_ALL_SUCCESS";
export const ORDER_ALL_FAIL = "ORDER_ALL_FAIL";
export const ORDER_ALL_RESET = "ORDER_ALL_RESET";

export const DELIVER_ORDER_ALL_REQUEST = "DELIVER_ORDER_ALL_REQUEST";
export const DELIVER_ORDER_ALL_SUCCESS = "DELIVER_ORDER_ALL_SUCCESS";
export const DELIVER_ORDER_ALL_FAIL = "DELIVER_ORDER_ALL_FAIL";
