export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAILS = "PRODUCT_LIST_FAILS";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILS = "PRODUCT_DETAILS_FAILS";

export const PRODUCT_ADD_REQUEST = "PRODUCT_ADD_REQUEST";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAILS = "PRODUCT_ADD_FAILS";

export const GET_PRODUCTBYID_REQUEST = "GET_PRODUCTBYID_REQUEST";
export const GET_PRODUCTBYID_SUCCESS = "GET_PRODUCTBYID_SUCCESS";
export const GET_PRODUCTBYID_FAILS = "GET_PRODUCTBYID_FAILS";

export const UPDATE_PRODUCTBYID_REQUEST = "UPDATE_PRODUCTBYID_REQUEST";
export const UPDATE_PRODUCTBYID_SUCCESS = "UPDATE_PRODUCTBYID_SUCCESS";
export const UPDATE_PRODUCTBYID_FAILS = "UPDATE_PRODUCTBYID_FAILS";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUCT_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUCT_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUCT_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUCT_CREATE_REVIEW_RESET";
