const products = [
  {
    _id: "1",
    name: "Tomato",
    image: "/images/tomatoes.jpg",
    description: "fresh",
    price: 50.5,
    countInStock: 20,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Potato",
    image: "/images/potatoes.jpg",
    description: "fresh",
    price: 50.5,
    countInStock: 20,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "lemon",
    image: "/images/Lemon.jpg",
    description: "fresh",
    price: 50.5,
    countInStock: 20,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Cucumbers",
    image: "/images/cucumbers.jpg",
    description: "fresh",
    price: 50.5,
    countInStock: 20,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Onion",
    image: "/images/Onions.jpeg",
    description: "fresh",
    price: 50.5,
    countInStock: 20,
    rating: 4,
    numReviews: 12,
  },
  {
    _id: "6",
    name: "Peas",
    image: "/images/Peas.jpg",
    description: "fresh",
    price: 50.5,
    countInStock: 20,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "7",
    name: "Ginger",
    image: "/images/ginger.jpg",
    description: "fresh",
    price: 50.5,
    countInStock: 20,
    rating: 4.5,
    numReviews: 17,
  },
  {
    _id: "7",
    name: "Chilli",
    image: "/images/Chilli.jpg",
    description: "fresh",
    price: 50.5,
    countInStock: 20,
    rating: 3.5,
    numReviews: 12,
  },
  {
    _id: "8",
    name: "Brinjal",
    image: "/images/Brinjal.jpg",
    description: "fresh",
    price: 50.5,
    countInStock: 20,
    rating: 4.5,
    numReviews: 12,
  },
];

export default products;
